### ISSUE TITLE
zip4j 2.0.3: when execute ZipFile.getInputStream(FileHeader), java.lang.ArrayIndexOutOfBoundsException happened.

### ISSUE THREAD

**Issue by dancencheung** [srikanth-lingala/zip4j#14]
**Code:**

	public static void main(String[] args)
	{
		try
		{
			String zipFilePath = "D:\\temp\\GoogleInstaller_3.0.zip";
			String filePathInZip = "classes.dex";
			ZipFile zipFile = new ZipFile(zipFilePath);				
			FileHeader fileHeader = zipFile.getFileHeader(filePathInZip);
			
			if(null != fileHeader && !fileHeader.isDirectory())
			{
				zipFile.getInputStream(fileHeader);
			}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}

**Exception:**
java.lang.ArrayIndexOutOfBoundsException: 3
	at net.lingala.zip4j.util.RawIO.readShortLittleEndian(RawIO.java:107)
	at net.lingala.zip4j.headers.HeaderReader.parseExtraDataRecords(HeaderReader.java:303)
	at net.lingala.zip4j.headers.HeaderReader.readExtraDataRecords(HeaderReader.java:279)
	at net.lingala.zip4j.headers.HeaderReader.readExtraDataRecords(HeaderReader.java:256)
	at net.lingala.zip4j.headers.HeaderReader.readCentralDirectory(HeaderReader.java:208)
	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:75)
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:831)
	at net.lingala.zip4j.ZipFile.getFileHeader(ZipFile.java:565)
	at com.dancen.util.filecompressor.MyZipUtil.main(MyZipUtil.java:37)

Usually, I can execute ZipFile.getInputStream(FileHeader) successfull, but for the file "GoogleInstaller_3.0.zip", ArrayIndexOutOfBoundsException throwed. I have attached the file.

[GoogleInstaller_3.0.zip](https://github.com/srikanth-lingala/zip4j/files/3371860/GoogleInstaller_3.0.zip)

**Comment by srikanth-lingala** [comment]
Technically speaking, this is a corrupt zip file. Without going into too many details, the issue with this zip file is that some header information is not as long as the length that should be for these headers. A block of zip headers tells how long certain headers (extra data records) are in the zip headers. This length is defined as 3 in this zip file, but this length has to be at least 4, and even 4 is wrong, but at least acceptable. Ideally it should be more than 4. But a length of 3 is definitely wrong.

However, this part of headers contain some additional information of the file, and the zip file can still be extracted even if these headers are corrupt. I will include a fix to skip these headers if these headers are corrupt. I will let you know when the fix is ready.

**Comment by srikanth-lingala** [comment]
Fixed in v2.1.0
