### ISSUE TITLE
Can't unzip with zip4j (java.util.zip - ok)

### ISSUE THREAD

**Issue by foobnix** [srikanth-lingala/zip4j#141]
Can't unzip (ZipFile) this book with zip4j but can with Java  java.util.zip
Please fix
[La media Naranja - Jose Alcala Galiano.epub.zip](https://github.com/srikanth-lingala/zip4j/files/4184681/La.media.Naranja.-.Jose.Alcala.Galiano.epub.zip)

net.lingala.zip4j.exception.ZipException: Zip headers not found. Probably not a zip file
        at net.lingala.zip4j.headers.HeaderReader.readEndOfCentralDirectoryRecord(HeaderReader.java:117)
        at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:73)
        at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:851)
        at net.lingala.zip4j.ZipFile.getFileHeaders(ZipFile.java:550)
        at com.foobnix.sys.ZipArchiveInputStream.<init>(ZipArchiveInputStream.java:41)
        at com.foobnix.sys.Zips.buildZipArchiveInputStream(Zips.java:6)

**Comment by srikanth-lingala** [comment]
Issue fixed. Will include in the next release.

**Comment by srikanth-lingala** [comment]
Fixed in v2.3.2 released today
