### ISSUE TITLE
Version 2.4.0 - Explicit termination method 'end' not called

### ISSUE THREAD

**Issue by vovan888** [srikanth-lingala/zip4j#155]
It looks like it happens when reading of ZipInputStream is interrupted.
I do ZipInputStream.close() but it is not enough.

D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1786)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
        at java.util.zip.Inflater.finalize(Inflater.java:398)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:221)
        at java.util.zip.Inflater.<init>(Inflater.java:114)
        at net.lingala.zip4j.io.inputstream.InflaterInputStream.<init>(InflaterInputStream.java:21)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.initializeDecompressorForThisEntry(ZipInputStream.java:206)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.initializeEntryInputStream(ZipInputStream.java:187)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.getNextEntry(ZipInputStream.java:103)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.getNextEntry(ZipInputStream.java:77)

**Comment by srikanth-lingala** [comment]
Is this specific to 2.4.0? Do you get this error also with older versions?

> It looks like it happens when reading of ZipInputStream is interrupted.

**Comment by srikanth-lingala** [comment]
I have fixed this issue. I will include the fix in the next release.

**Comment by srikanth-lingala** [comment]
I included this fix in a release, v2.5.0, I had to do today. I think the code change I did will fix this issue. If not, please reopen this issue again with your findings.  

And also: a couple of more features have been added in this release. Please have a look at [release notes][1].

[1]: https://github.com/srikanth-lingala/zip4j/releases

**Comment by vovan888** [comment]
Thank you so much! The issue is fixed in v2.5.0
