### ISSUE TITLE
2.1.0 closable leak when extracting zip file

### ISSUE THREAD

**Issue by richstokes129** [srikanth-lingala/zip4j#17]
when calling ZipFile.extractAll with StrictMode on there is a crash due to a unclosed resource.

Similar to issue https://github.com/srikanth-lingala/zip4j/issues/3

'mainapp E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:282)
        at net.lingala.zip4j.io.inputstream.SplitInputStream.<init>(SplitInputStream.java:22)
        at net.lingala.zip4j.tasks.ExtractAllFilesTask.prepareZipInputStream(ExtractAllFilesTask.java:59)
        at net.lingala.zip4j.tasks.ExtractAllFilesTask.executeTask(ExtractAllFilesTask.java:26)
        at net.lingala.zip4j.tasks.ExtractAllFilesTask.executeTask(ExtractAllFilesTask.java:13)
        at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:41)
        at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:35)
        at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:431)'

**Comment by srikanth-lingala** [comment]
After analysing this, I think the only way it happens currently is when you enter wrong password for an AES encrypted zip file. In this case, I see a bug that does not close the resource properly. Can you please confirm if you got this in the same circumstances? If not, it would be great if you can post your code and also, if possible, the zip file with which this happens. Thanks.

**Comment by srikanth-lingala** [comment]
As I did not get any further feedback to my question, I presume that this exception occurs only in the scenario outlined in my comment above. I have included a fix for it in version 2.1.1 which is released today. If you still get this exception, please reopen this issue along with your code sample and if possible also the zip file. Thanks.
