### ISSUE TITLE
Compatible maven plugin and java versions for 2.6.1 version of zip4j

### ISSUE THREAD

**Issue by rvikram366** [srikanth-lingala/zip4j#203]
i am using the 2.6.1 version of zip4j in my project(spring 3). While maven build the project i am getting below error. if i use 1.3.2 version of zip4j built is getting success.

java.lang.ArrayIndexOutOfBoundsException: 52264
	at com.bea.objectweb.asm.ClassReader.readClass(Unknown Source)
	at com.bea.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.bea.objectweb.asm.ClassReader.accept(Unknown Source)
	at weblogic.application.utils.annotation.ClassInfoImpl.<init>(ClassInfoImpl.java:52)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.polulateOneClassInfo(ClassfinderClassInfos.java:170)

[ERROR] Exception encountered during APPC processing 
weblogic.utils.compiler.ToolFailureException: 52264
	at weblogic.ant.taskdefs.j2ee.CompilerTask.invokeMain(CompilerTask.java:310)
	at weblogic.ant.taskdefs.j2ee.Appc.privateExecute(Appc.java:261)
	at weblogic.ant.taskdefs.j2ee.Appc.execute(Appc.java:164)
	at org.codehaus.mojo.weblogic.AppcMojo.execute(AppcMojo.java:191)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)

**Comment by rvikram366** [comment]
Need to know the compatability changes from 1.3.2 verison to latest version.

**Comment by srikanth-lingala** [comment]
Unfortunately, it is quite difficult for me to know the reason of the issue, and the stack trace does not help much here. Did you figure out the issue in the mean time?

**Comment by srikanth-lingala** [comment]
Closing this issue as there was no feedback from the user. Please feel free to reopen if you have any feedback for my previous post in this issue.

**Comment by rvikram366** [comment]
Hi Srikanth,

Sorry for the late reply.
As I mentioned in my previous emails, it didn't worked with lower version.
So I used the higher version of the jar. With that it worked.

Thanks,
Vikram.
