### ISSUE TITLE
net.lingala.zip4j.exception.ZipException: invalid offsets

### ISSUE THREAD

**Issue by YeChenLiu** [srikanth-lingala/zip4j#220]
net.lingala.zip4j.exception.ZipException: invalid offsets
	at net.lingala.zip4j.util.FileUtils.copyFile(FileUtils.java:287)
	at net.lingala.zip4j.tasks.AbstractModifyFileTask.copyFile(AbstractModifyFileTask.java:70)
	at net.lingala.zip4j.tasks.RemoveFilesFromZipTask.executeTask(RemoveFilesFromZipTask.java:66)
	at net.lingala.zip4j.tasks.RemoveFilesFromZipTask.executeTask(RemoveFilesFromZipTask.java:21)
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:44)
	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:38)
	at net.lingala.zip4j.ZipFile.removeFiles(ZipFile.java:716)
	at net.lingala.zip4j.ZipFile.removeFile(ZipFile.java:684)

An exception occurred when deleting the zip file

**Comment by srikanth-lingala** [comment]
Can you attach the zip file? Which version of zip4j are you on?

**Comment by YeChenLiu** [comment]
[abc.zip](https://github.com/srikanth-lingala/zip4j/files/4946701/abc.zip)
version ：2.6.1
remark ： Apk uploads are not supported, so zip is uploaded. You need to unzip the ZIP

**Comment by srikanth-lingala** [comment]
Thanks for the zip file. I was able to reproduce it. Working on a fix.

**Comment by srikanth-lingala** [comment]
Issue fixed in v2.6.2 released today.
