### ISSUE TITLE
Provided EncryptionMethod.ZIP_STANDARD_VARIANT_STRONG is not supported

### ISSUE THREAD

**Issue by SorinBela** [srikanth-lingala/zip4j#237]
Trying to create a _ZipFile_ with _EncryptionMethod.ZIP_STANDARD_VARIANT_STRONG_ yields an _ZipException_: "Invalid encryption method".

This is because _ZipOutputStream::CipherOutputStream_ does not accept _EncryptionMethod.ZIP_STANDARD_VARIANT_STRONG_

StackTrace:

```java
 net.lingala.zip4j.exception.ZipException: Invalid encryption method

	at net.lingala.zip4j.io.outputstream.ZipOutputStream.initializeCipherOutputStream(ZipOutputStream.java:193)
	at net.lingala.zip4j.io.outputstream.ZipOutputStream.initializeCompressedOutputStream(ZipOutputStream.java:174)
	at net.lingala.zip4j.io.outputstream.ZipOutputStream.putNextEntry(ZipOutputStream.java:74)
	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFileToZip(AbstractAddFileToZipTask.java:108)
	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:84)
	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:26)
	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:15)
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
	at net.lingala.zip4j.ZipFile.addFiles(ZipFile.java:292)
	at net.lingala.zip4j.ZipFile.addFile(ZipFile.java:245)
```

**Comment by srikanth-lingala** [comment]
`ZIP_STANDARD_VARIANT_STRONG` is not supported by zip4j because this encryption method is patent protected by PKWare and implementing this encryption method requires a license from PKWare. The reason it exists as an enum in zip4j is because clients can at least know the encryption method if an entry in zip is encrypted with this method.

**Comment by drewfeelsblue** [comment]
hi, @srikanth-lingala 

Maybe it is worth leaving a comment in the enum to make it clear for library users?
