### ISSUE TITLE
Got Wrong Password ZipException when trying unzip archive with password created with PHP

### ISSUE THREAD

**Issue by Stafox** [srikanth-lingala/zip4j#265]
I faced with problem when trying extract the archive with AES256 encryption created with PHP.

```
Filesystem Error Error: Failed to unzip file, due to: net.lingala.zip4j.exception.ZipException: Wrong Password
	at net.lingala.zip4j.crypto.AESDecrypter.init(AESDecrypter.java:61)
	at net.lingala.zip4j.crypto.AESDecrypter.<init>(AESDecrypter.java:49)
	at net.lingala.zip4j.io.inputstream.AesCipherInputStream.initializeDecrypter(AesCipherInputStream.java:37)
	at net.lingala.zip4j.io.inputstream.AesCipherInputStream.initializeDecrypter(AesCipherInputStream.java:18)
	at net.lingala.zip4j.io.inputstream.CipherInputStream.<init>(CipherInputStream.java:25)
	at net.lingala.zip4j.io.inputstream.AesCipherInputStream.<init>(AesCipherInputStream.java:32)
	at net.lingala.zip4j.io.inputstream.ZipInputStream.initializeCipherInputStream(ZipInputStream.java:196)
	at net.lingala.zip4j.io.inputstream.ZipInputStream.initializeEntryInputStream(ZipInputStream.java:186)
	at net.lingala.zip4j.io.inputstream.ZipInputStream.getNextEntry(ZipInputStream.java:103)
	at net.lingala.zip4j.tasks.AbstractExtractFileTask.verifyNextEntry(AbstractExtractFileTask.java:136)
	at net.lingala.zip4j.tasks.AbstractExtractFileTask.extractFile(AbstractExtractFileTask.java:52)
	at net.lingala.zip4j.tasks.ExtractFileTask.executeTask(ExtractFileTask.java:39)
	at net.lingala.zip4j.tasks.ExtractFileTask.executeTask(ExtractFileTask.java:21)
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
	at net.lingala.zip4j.ZipFile.extractFile(ZipFile.java:485)
	at net.lingala.zip4j.ZipFile.extractFile(ZipFile.java:451)
	at com.rnziparchive.RNZipArchiveModule$1.run(RNZipArchiveModule.java:98)
```

Here is how I create the archive:
```php
$zip = new ZipArchive();
$password = 'rTyUi8&6%zXcV';
$zipPath = './zippedfile.txt.zip';

if ($zip->open($zipPath, ZipArchive::CREATE|ZipArchive::OVERWRITE) === true) {
    $zip->addFile('./zippedfile.txt', 'zippedfile.txt');

    $zip->setPassword($password);
    $zip->setEncryptionName('zippedfile.txt', ZipArchive::EM_AES_256);

    $zip->close();
}
``` 

There is a PHP documentation: https://www.php.net/manual/en/ziparchive.setencryptionname.php

I do unzip in React Native project using https://github.com/mockingbot/react-native-zip-archive library.
Have tried release 5.0.7-beta.3 which bring zip4j v.2.6.4

Attached zipped file and zip archive as example.
Password is `rTyUi8&6%zXcV`

BTW I able to extract archive as using PHP and Swift using SSZipArchive lib.

[zippedfile.txt](https://github.com/srikanth-lingala/zip4j/files/5626154/zippedfile.txt)
[zippedfile.txt.zip](https://github.com/srikanth-lingala/zip4j/files/5626155/zippedfile.txt.zip)

**Comment by srikanth-lingala** [comment]
Hey, apologies for my delayed reply.  I was a bit busy the last days. I will look into it and let you know.

**Comment by srikanth-lingala** [comment]
When I try to extract the zip file from Java, it works fine for me. Unfortunately, I am not familiar with PHP, so I can't say what is going wrong with your code, but zip4j is able to extract the zip file successfully. Here's the code I used in Java:

```
  @Test
  public void testIssue246() throws IOException {
    ZipFile zipFile = new ZipFile(BASE_DIR + "zippedfile.txt.zip", "rTyUi8&6%zXcV".toCharArray());
    zipFile.extractAll(OUTPUT_DIR);
  }
```

**Comment by Stafox** [comment]
> When I try to extract the zip file from Java, it works fine for me. Unfortunately, I am not familiar with PHP, so I can't say what is going wrong with your code, but zip4j is able to extract the zip file successfully. Here's the code I used in Java:
> 
> ```
>   @Test
>   public void testIssue246() throws IOException {
>     ZipFile zipFile = new ZipFile(BASE_DIR + "zippedfile.txt.zip", "rTyUi8&6%zXcV".toCharArray());
>     zipFile.extractAll(OUTPUT_DIR);
>   }
> ```

Hm, thanks. Will take a deep look and get back. Maybe an issue in passing password between RN lib and zip4j.
Thanks for your response..

**Comment by Stafox** [comment]
@srikanth-lingala found a clear way to reproduce it.

The problem is in password.

I tried this one `rЯyUi8&6%zXcV`. The second character is cyrillic symbol.

Have attached zip encrypted with rЯyUi8&6%zXcV`.
[zippedfile.txt.zip](https://github.com/srikanth-lingala/zip4j/files/5642472/zippedfile.txt.zip)

**Comment by srikanth-lingala** [comment]
In this case, the password seems to be indeed wrong. Not just with zip4j, but I cannot extract the zip file with any other zip tools as well.

**Comment by Stafox** [comment]
It can be useful to have a note in readme.

BTW I unzipped it successfully on iOS using SSZipArchive and `p7zip` on MacOS terminal.
