### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by EmmanuelMess** [srikanth-lingala/zip4j#280]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux
htc/htc_bre_dugl_00400/htc_breeze_dugl:7.1.1/N6F26Q/191009:user/release-keys
7.1.1 - 25
* __Device:__ htc_breeze_dugl
* __Model:__ HTC Desire 12
* __Product:__ htc_bre_dugl_00400
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing
doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:325)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
at net.lingala.zip4j.util.Raw.readShortLittleEndian(Raw.java:57)
at
net.lingala.zip4j.core.HeaderReader.readExtraDataRecords(HeaderReader.java:468)
at
net.lingala.zip4j.core.HeaderReader.readAndSaveExtraDataRecord(HeaderReader.java:420)
at
net.lingala.zip4j.core.HeaderReader.readCentralDirectory(HeaderReader.java:338)
at net.lingala.zip4j.core.HeaderReader.readAllHeaders(HeaderReader.java:94)
at net.lingala.zip4j.core.ZipFile.readZipInfo(ZipFile.java:425)
at net.lingala.zip4j.core.ZipFile.getFileHeaders(ZipFile.java:688)
at
com.amaze.filemanager.asynchronous.asynctasks.compress.ZipHelperTask.addElements(ZipHelperTask.java:77)
at
com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperTask.doInBackground(CompressedHelperTask.java:58)
at
com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperTask.doInBackground(CompressedHelperTask.java:37)
at android.os.AsyncTask$2.call(AsyncTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more

```
</details>
<hr>

**Comment by srikanth-lingala** [comment]
Which version of zip4j are you using? Your [build.gradle][1] points to zip4j v2.6.4 but the stacktrace does not correspond to that version. For example, there is no Raw.java in 2.6.4 as indicated in your stacktrace. This was renamed to RawIO a few versions back. And also, in 2.6.4, HeaderReader.readExtraDataRecords does not call Raw.readShortLittleEndian directly, but uses a different layer on top. It might be that it is fixed in the latest version. If the issue still exists in the latest version, please post the stacktrace related to the latest version of zip4j.

[1]: https://github.com/TeamAmaze/AmazeFileManager/blob/release/3.6/app/build.gradle#L115

**Comment by EmmanuelMess** [comment]
1.3.2. The build gradle you selected is not the last release's one, [this](https://github.com/TeamAmaze/AmazeFileManager/blob/v3.5.3/app/build.gradle#L115) one is.

**Comment by EmmanuelMess** [comment]
> If the issue still exists in the latest version, please post the stacktrace related to the latest version of zip4j.

No problem.
