### ISSUE TITLE
File name is null, cannot determine file header with exact match for fileName:  

### ISSUE THREAD

**Issue by JarFiles** [srikanth-lingala/zip4j#281]
Some customers were reporting this issue. For some reason the fileName is sometimes null. Any ideas why this could be happening?
```JAVA
  if (!isStringNotNullAndNotEmpty(fileName)) {
      throw new ZipException("file name is null, cannot determine file header with exact match for fileName: "
          + fileName);
    }
```

Or is there any way how I could ignore this error?

**Comment by blek-id** [comment]
I'm the customer reporting the issue, let me know if I can provide any extra info for the bug.

**Comment by srikanth-lingala** [comment]
Which version of zip4j are you using?
Would you be able to provide me with a working sample (code + zip file) to reproduce this issue?
Is the file that you are trying to find a directory or is it a file under a subdirectory (i.e, the file is not at the root of the zip flie)?

**Comment by blek-id** [comment]
zip4j version can be answered by @JarFiles 
as for the working sample I don't think we can provide it because the directory is very large.

**Comment by JarFiles** [comment]
I am using version 2.6.4-SNAPSHOT,
the directory is added by using ZipFile#addFolder

**Comment by srikanth-lingala** [comment]
Can you maybe provide an example for a file name for which this has happened? What was the name of the file that was printed out as part of the exception, and what are the names of all files in the zip file? You can print out the names of the files in the zip file with the code below. If you can share it, and do not want to post it publicly, you can also send me an email. My email in [last section of README][1].

`ZipFile.getFileHeaders().forEach(e -> System.out.println(e.getFileName()));`

 This could be happening for several reasons, and it would be quite difficult for me to say what might be going wrong without any further input. As mentioned in my previous post, it might be an operating system file separator issue (although zip4j checks for both backslash and forward slash in file names), it might be a unicode issue, or there could be several other possibilities. Any input might be helpful.

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/README.md

**Comment by kelvin-junilson** [comment]
I'll be able to share it publicly, waiting for @JarFiles to share the code for me to check for the file names.

**Comment by blek-id** [comment]
I will provide the result of the console log after @JarFiles provided me with the jar files with the modified code

**Comment by JarFiles** [comment]
> ZipFile.getFileHeaders().forEach(e -> System.out.println(e.getFileName()));

Where exactly shall I put this line? After the folder has been added?

**Comment by srikanth-lingala** [comment]
This code can be independent of your code. A small standalone main() method or a Junit test method. All I want to see is the list of file names in the zip, and the file name being printed in the exception message. 

Just to confirm: You are most likely using `ZipFile.extractFile()` method when you get this exception, right? 

And BTW, why are you using a `SNAPSHOT` version and why not use a production version?

**Comment by JarFiles** [comment]
> Just to confirm: You are most likely using `ZipFile.extractFile()` method when you get this exception, right?

No, this is happening while adding a folder to an empty zip file. That's why I am asking

> And BTW, why are you using a `SNAPSHOT` version and why not use a production version?

Because this also happened in previous production versions and I simply haven't updated my application after the official 2.6.4 was released.

**Comment by srikanth-lingala** [comment]
Can you post the complete stacktrace please?

**Comment by JarFiles** [comment]
```[00:00:22] [pool-22-thread-6/INFO]: Full Stacktrace:
[00:00:22] [pool-22-thread-6/WARN]: me.forseth11.easybackup.dependencies.zip4j.exception.ZipException: file name is null, cannot determine file header with exact match for fileName:  
[00:00:22] [pool-22-thread-6/WARN]: 	at me.forseth11.easybackup.dependencies.zip4j.headers.HeaderUtil.getFileHeaderWithExactMatch(HeaderUtil.java)
[00:00:22] [pool-22-thread-6/WARN]: 	at me.forseth11.easybackup.dependencies.zip4j.headers.HeaderUtil.getFileHeader(HeaderUtil.java)
[00:00:22] [pool-22-thread-6/WARN]: 	at me.forseth11.easybackup.dependencies.zip4j.tasks.AbstractAddFileToZipTask.calculateWorkForFiles(AbstractAddFileToZipTask.java)
[00:00:22] [pool-22-thread-6/WARN]: 	at me.forseth11.easybackup.dependencies.zip4j.tasks.AddFolderToZipTask.calculateTotalWork(AddFolderToZipTask.java)
[00:00:22] [pool-22-thread-6/WARN]: 	at me.forseth11.easybackup.dependencies.zip4j.tasks.AddFolderToZipTask.calculateTotalWork(AddFolderToZipTask.java)
[00:00:22] [pool-22-thread-6/WARN]: 	at me.forseth11.easybackup.dependencies.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java)
[00:00:22] [pool-22-thread-6/WARN]: 	at me.forseth11.easybackup.dependencies.zip4j.ZipFile.addFolder(ZipFile.java)
[00:00:22] [pool-22-thread-6/WARN]: 	at me.forseth11.easybackup.dependencies.zip4j.ZipFile.addFolder(ZipFile.java)
[00:00:22] [pool-22-thread-6/WARN]: 	at me.forseth11.easybackup.ca.a(ca.java)
[00:00:22] [pool-22-thread-6/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[00:00:22] [pool-22-thread-6/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[00:00:22] [pool-22-thread-6/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[00:00:22] [pool-22-thread-6/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[00:00:22] [pool-22-thread-6/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by srikanth-lingala** [comment]
The issue seems to be somewhere in [this method][1]. It will be quite hard to say what is going wrong with this method as it heavily depends on the input parameters to this method. It depends on the value of `fileToAdd` and the value set in `zipParameters.getDefaultFolderPath()`. Are you also able to debug this issue? It would be super interesting to know the values of those parameters when this issue occurs.

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/util/FileUtils.java#L206

**Comment by srikanth-lingala** [comment]
I have added some more info to the exception message to see the values of those parameters (as mentioned above). Can you try with the snapshot version `2.6.5.1-SNAPSHOT` and post the stacktrace here please?  If you have trouble accessing the snapshot version, please check [this][1] answer.

[1]: https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository

**Comment by JarFiles** [comment]
Will do, could take some time though

**Comment by srikanth-lingala** [comment]
A new version of zip4j `2.7.0` is released today. I have included this commit in the release so that you don't have to use a snapshot version until we identify and fix this issue. I have also improved the exception message which will give me some more info to identify this issue. Please use this version. 

I will leave this issue open for now. Please post the stacktrace (along with the complete exception message) when you have it.

**Comment by blek-id** [comment]
Found the file with the issue. It's a file with no name and no extension. I have no idea what created it but it's there and it's the main issue. 
![image](https://user-images.githubusercontent.com/26654664/108798211-d8b6e400-75bf-11eb-803b-75f2d79c56f7.png)

**Comment by srikanth-lingala** [comment]
Which OS is it? There are two options to fix it: 

* Ignore such files
* Give it an explicit name

I am a bit tempted to ignore the files, because giving those files a name might lead to some other unexpected issues. Ignoring the files will also improve the compatibility of the zip file, because files without any names cannot be extracted anyway to most of the operating systems. I wonder how other zip tools react when such files are added to a zip file. Can you please try to zip the folder containing this file and see what happens? Is the file included in the zip file? If yes, does it have a different name than an empty string?

**Comment by blek-id** [comment]
I'm on Ubuntu 18.04 but this shouldn't be a problem because the file is not needed anymore, actually I don't even know where the file came from haha. So deleting the file solves everything.

To prevent this from causing headache for you and for @JarFiles, giving debug for where the troubled file location directory is would be really great (if that's possible ofc, I have no idea how JarFiles' implementation of zip4j or even how zip4j works)

**Comment by srikanth-lingala** [comment]
Fixed in v2.8.0 released today.
