### ISSUE TITLE
1.3.3 leaks Deflate resource on Android

### ISSUE THREAD

**Issue by Gericop** [srikanth-lingala/zip4j#3]
Calling `zipFile.addStream(inputStream, zipParameters)` calls `zipEngine.addStreamToZip(...)` which creates a `ZipOutputStream` which is a `DeflaterOutputStream` that has a `Deflate` member. This `Deflate` member should be closed using the `end()` method which is never called.

**Comment by richstokes129** [comment]
This has issue has also been found on 1.3.2 and 1.3.3 on createZipFileFromFolder(...), addFolder(...), addFiles(....)

Stack trace from 1.3.3 with Strict mode enable with detectLeakedClosableObjects() turned on:

E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.util.zip.Deflater.<init>(Deflater.java:173)
        at java.util.zip.Deflater.<init>(Deflater.java:190)
        at net.lingala.zip4j.io.DeflaterOutputStream.<init>(DeflaterOutputStream.java:38)
        at net.lingala.zip4j.io.ZipOutputStream.<init>(ZipOutputStream.java:15)
        at net.lingala.zip4j.zip.ZipEngine.initAddFiles(ZipEngine.java:114)
        at net.lingala.zip4j.zip.ZipEngine.addFiles(ZipEngine.java:85)
        at net.lingala.zip4j.zip.ZipEngine.addFolderToZip(ZipEngine.java:297)
        at net.lingala.zip4j.core.ZipFile.addFolder(ZipFile.java:356)
        at net.lingala.zip4j.core.ZipFile.createZipFileFromFolder(ZipFile.java:236)

**Comment by srikanth-lingala** [comment]
Fixed in version 2.0 released today (it might be a few hours before the version is synced to maven central).

Please note that v2.0 is a major change from the previous versions. Please have a look at the [usage section of the readme][1] for more details.

[1]: https://github.com/srikanth-lingala/zip4j#usage
