### ISSUE TITLE
Error creating splitted archive

### ISSUE THREAD

**Issue by anal-probe** [srikanth-lingala/zip4j#308]
version 2.7.0

**Code**
ZipFile zipFile = new ZipFile("test.zip");
zipFile.createSplitZipFile(filesToAdd, new ZipParameters(), true, 1024*1024);

**Error**
Caused by: java.io.FileNotFoundException: null/test.z01 (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at net.lingala.zip4j.io.outputstream.SplitOutputStream.<init>(SplitOutputStream.java:51)
	at net.lingala.zip4j.io.outputstream.SplitOutputStream.<init>(SplitOutputStream.java:43)
	at net.lingala.zip4j.headers.HeaderWriter.updateLocalFileHeader(HeaderWriter.java:272)
	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.updateLocalFileHeader(AbstractAddFileToZipTask.java:197)
	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.closeEntry(AbstractAddFileToZipTask.java:137)
	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFileToZip(AbstractAddFileToZipTask.java:122)
	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:85)
	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:27)
	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:15)
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
	... 22 more

**Workaround**
Create ZipFile with full path:
ZipFile zipFile = new ZipFile("/tmp/test.zip");

**Comment by srikanth-lingala** [comment]
Thanks for reporting the issue. I will test and fix this in the next release.

**Comment by srikanth-lingala** [comment]
Fixed in v2.8.0 released today.
