### ISSUE TITLE
EFBIG Error when zipping

### ISSUE THREAD

**Issue by bonitahlee** [srikanth-lingala/zip4j#320]
### I'm trying to zip Flashdisk and its size is 32GB.
but it always got error from progressMonitor.getResult().
and zip file is corrupted and its size is 4GB always!

First. sorry for the wrong format. i'm not used to GITHUB

**I'm using  version  2.7.0**
`implementation group: 'net.lingala.zip4j', name: 'zip4j', version: '2.7.0'`
**gradle version `4.8.1-bin.zip`**
**`compileSdkVersion, targetSdkVersion 29`**
buildToosVersion '30.0.2'
gradle classpath  classpath `'com.android.tools.build:gradle:3.0.1'`
JDK 1.8 and add compileOptions     
```
compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
```

### Here is my code.

```
 final ZipParameters parameters = new ZipParameters();
 parameters.setCompressionMethod(CompressionMethod.STORE);
 parameters.setIncludeRootFolder(false);

final ZipFile zipFile = new ZipFile("/storage/SDCARD/sample.zip");
zipFile.setRunInThread(true);
zipFile.addFolder(new File("/storage/emulated/0"), parameters);
```

### **This is the log i received.**

```
W/System.err: java.io.IOException: write failed: EFBIG (File too large)
W/System.err: at libcore.io.IoBridge.write(IoBridge.java:544)
W/System.err: at java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:546)
W/System.err: at java.io.RandomAccessFile.write(RandomAccessFile.java:572)
W/System.err: at net.lingala.zip4j.io.outputstream.SplitOutputStream.write(SplitOutputStream.java:72)
W/System.err: at net.lingala.zip4j.io.outputstream.CountingOutputStream.write(CountingOutputStream.java:29)
W/System.err: at net.lingala.zip4j.io.outputstream.ZipEntryOutputStream.write(ZipEntryOutputStream.java:33)
W/System.err: at net.lingala.zip4j.io.outputstream.CipherOutputStream.write(CipherOutputStream.java:50)
W/System.err: at net.lingala.zip4j.io.outputstream.CompressedOutputStream.write(CompressedOutputStream.java:26)
W/System.err: at net.lingala.zip4j.io.outputstream.DeflaterOutputStream.deflate(DeflaterOutputStream.java:55)
W/System.err: at net.lingala.zip4j.io.outputstream.DeflaterOutputStream.write(DeflaterOutputStream.java:48)
W/System.err: at net.lingala.zip4j.io.outputstream.ZipOutputStream.write(ZipOutputStream.java:93)
W/System.err: at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFileToZip(AbstractAddFileToZipTask.java:115)
W/System.err: at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:85)
W/System.err: at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:28)
W/System.err: at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:17)
W/System.err: at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
W/System.err: at net.lingala.zip4j.tasks.AsyncZipTask.lambda$execute$0$AsyncZipTask(AsyncZipTask.java:32)
W/System.err: at net.lingala.zip4j.tasks.AsyncZipTask$$Lambda$0.run(Unknown Source:4)
W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err: at java.lang.Thread.run(Thread.java:919)
W/System.err: Suppressed: java.io.IOException: write failed: EFBIG (File too large)
W/System.err: at libcore.io.IoBridge.write(IoBridge.java:544)
W/System.err: at java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:546)
W/System.err: at java.io.RandomAccessFile.write(RandomAccessFile.java:572)
W/System.err: at net.lingala.zip4j.io.outputstream.SplitOutputStream.write(SplitOutputStream.java:72)
W/System.err: at net.lingala.zip4j.io.outputstream.CountingOutputStream.write(CountingOutputStream.java:29)
W/System.err: at net.lingala.zip4j.io.outputstream.CountingOutputStream.write(CountingOutputStream.java:24)
W/System.err: at net.lingala.zip4j.headers.HeaderWriter.writeZipHeaderBytes(HeaderWriter.java:354)
W/System.err: at net.lingala.zip4j.headers.HeaderWriter.finalizeZipFile(HeaderWriter.java:213)
W/System.err: at net.lingala.zip4j.io.outputstream.ZipOutputStream.close(ZipOutputStream.java:125)
W/System.err: at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:87)
W/System.err: ... 8 more
W/System.err: Caused by: android.system.ErrnoException: write failed: EFBIG (File too large)
W/System.err: at libcore.io.Linux.writeBytes(Native Method)
W/System.err: at libcore.io.Linux.write(Linux.java:294)
W/System.err: at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
W/System.err: at libcore.io.BlockGuardOs.write(BlockGuardOs.java:416)
W/System.err: at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
W/System.err: at libcore.io.IoBridge.write(IoBridge.java:539)
W/System.err: ... 17 more
W/System.err: Caused by: android.system.ErrnoException: write failed: EFBIG (File too large)
W/System.err: at libcore.io.Linux.writeBytes(Native Method)
W/System.err: at libcore.io.Linux.write(Linux.java:294)
W/System.err: at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
W/System.err: at libcore.io.BlockGuardOs.write(BlockGuardOs.java:416)
W/System.err: at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
W/System.err: at libcore.io.IoBridge.write(IoBridge.java:539)
W/System.err: ... 20 more
```

Thanks in advance!

**Comment by bonitahlee** [comment]
Sorry. I found that my SDCARD is FAT32 format. so it couldn't be fixed..
