### ISSUE TITLE
NoClassDefFoundError : StandardCharsets  in Android 4.3

### ISSUE THREAD

**Issue by abbasalim** [srikanth-lingala/zip4j#321]
in old android give this error:

`....
 Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at net.lingala.zip4j.util.Zip4jUtil.convertCharArrayToByteArray(Zip4jUtil.java:103)
        at net.lingala.zip4j.crypto.engine.ZipCryptoEngine.initKeys(ZipCryptoEngine.java:44)
        at net.lingala.zip4j.crypto.StandardEncrypter.init(StandardEncrypter.java:39)
        at net.lingala.zip4j.crypto.StandardEncrypter.<init>(StandardEncrypter.java:32)
        at net.lingala.zip4j.io.outputstream.ZipStandardCipherOutputStream.initializeEncrypter(ZipStandardCipherOutputStream.java:21)
        at net.lingala.zip4j.io.outputstream.ZipStandardCipherOutputStream.initializeEncrypter(ZipStandardCipherOutputStream.java:10)
        at net.lingala.zip4j.io.outputstream.CipherOutputStream.<init>(CipherOutputStream.java:34)
        at net.lingala.zip4j.io.outputstream.ZipStandardCipherOutputStream.<init>(ZipStandardCipherOutputStream.java:14)
        at net.lingala.zip4j.io.outputstream.ZipOutputStream.initializeCipherOutputStream(ZipOutputStream.java:196)
        at net.lingala.zip4j.io.outputstream.ZipOutputStream.initializeCompressedOutputStream(ZipOutputStream.java:179)
        at net.lingala.zip4j.io.outputstream.ZipOutputStream.putNextEntry(ZipOutputStream.java:79)
        at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFileToZip(AbstractAddFileToZipTask.java:110)
        at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:85)
        at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:28)
        at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:17)
        at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
        at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
        at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:391)
        at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:366)
.....`

**Comment by abbasalim** [comment]
this error occure in version 2.7, no problem in 2.6.4

**Comment by srikanth-lingala** [comment]
Fixed it. I will include the fix in the next release.

**Comment by srikanth-lingala** [comment]
Fixed in v2.8.0 released today.
