### ISSUE TITLE
Exception raised when zipping a symbolic link

### ISSUE THREAD

**Issue by DevLazio** [srikanth-lingala/zip4j#433]
When trying to zip a folder containing a symbolic link to /tmp/ I encounter the following error :

```
net.lingala.zip4j.exception.ZipException: java.lang.StringIndexOutOfBoundsException: String index out of range: -5
        at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:58)
        at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:45)
        at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:390)
        at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:365)
```

I'm trying to zip a folder with this structure : 
![image](https://user-images.githubusercontent.com/2280811/171902161-51b1d072-e048-4cfd-b657-971217d9d885.png)
[cogi8.zip](https://github.com/srikanth-lingala/zip4j/files/8833981/cogi8.zip) 

Changing the SymbolicLinkAction did not help.

**Comment by srikanth-lingala** [comment]
Fixed in v2.11.0 released today

**Comment by Hronom** [comment]
Hey @srikanth-lingala still valid in `2.11.0`, I'm trying to zip this repository https://github.com/JetBrains/compose-jb and get error

```
Symlink target '../../../../../../../prebuilts/androidx/exoplayer/exoplayer-media2.jar' does not exist for link '{hided}/compose-jb/compose/frameworks/support/media2/media2-exoplayer/src/main/libs/exoplayer-media2.jar'
```

Here my code on Kotlin:
```
        val zipParameters = ZipParameters()
        zipParameters.isOverrideExistingFilesInZip = true
        zipParameters.compressionLevel = CompressionLevel.ULTRA

        val file = File("$absolutePath.zip")
        file.delete()

        ZipFile(file).use {
            it.isRunInThread = true
            val progressMonitor = it.progressMonitor
            it.addFolder(File(absolutePath), zipParameters)
            while (!progressMonitor.state.equals(ProgressMonitor.State.READY)) {
                onProgress(progressMonitor.percentDone)
                println(progressMonitor.percentDone)
                delay(1000L)
            }
            if (progressMonitor.result.equals(ProgressMonitor.Result.ERROR)) {
                throw IllegalStateException(progressMonitor.exception)
            }
        }
```
Java 17

**Comment by Hronom** [comment]
Oh looks like able to solve by adding this param:
```
        zipParameters.symbolicLinkAction = ZipParameters.SymbolicLinkAction.INCLUDE_LINK_ONLY
```
