### ISSUE TITLE
When using JDK's zipInputStream to decorate zip4j, due to the CRC32 mechanism, a close stream exception will be generated

### ISSUE THREAD

**Issue by laglangyue** [srikanth-lingala/zip4j#515]
1
Use JDK zipInputStream to writer a paraent zipFile which contains some zipFile.
2
use zip4j open this zip，and use JDK zipInputStream open the inner zipFile，when close zipInputSteam. it exceptioned.

```java
Suppressed: java.io.IOException: invalid CRC for file: 74193495856f4761b60d035d64e3c408/resource/bca7e8181b00455fa33ee988f7b73bb9-all.zip
		at net.lingala.zip4j.io.ZipInputStream.close(ZipInputStream.java:77)
		at net.lingala.zip4j.io.ZipInputStream.close(ZipInputStream.java:60)
```

**Comment by laglangyue** [comment]
![image](https://github.com/srikanth-lingala/zip4j/assets/35491928/e5e90dd2-4cab-464b-aecc-846fe04b307d)
because the JDK will use close() method

**Comment by laglangyue** [comment]
I'm not sure if this can be optimized, should CRC be verified by default

**Comment by laglangyue** [comment]
I find my version is 1.x，but now it support 2.x.
I think 2. x should no longer have this issue.
