### ISSUE TITLE
Zip4J Regression Failure v2.7.0+ | Unzip Crypted Files Created with ZLIB

### ISSUE THREAD

**Issue by RohdeSchwarz-SDC** [srikanth-lingala/zip4j#522]
Hello community,

Recently, I noticed a regression failure when unzipping encrypted files which were created by the C++ zlib library.
The failure occurred after updating from version 2.6.4 to 2.7.0 (up to latest 2.11.5)

In such cases the following Exception is thrown:
`net.lingala.zip4j.exception.ZipException: Wrong password!`
`     at net.lingala.zip4j.crypto.StandardDecrypter.init(StandardDecrypter.java:63)`
`     at net.lingala.zip4j.crypto.StandardDecrypter.<init>(StandardDecrypter.java:32)`
`     at net.lingala.zip4j.io.inputstream.ZipStandardCipherInputStream.initializeDecrypter`
`     ...`

It would be great, if we could find any solution (maybe introducing an ZLIB-Compatiblity-Option in your API?)

**Comment by RohdeSchwarz-SDC** [comment]
Found the cause of exception: Our zip files had a wrong CRC.

I don't know any implementation details of zip4j library, but is it possible to differentiate between a wrong CRC vs. wrong password?

In any case it would be useful to modify the exception message to cover both cases.

**Comment by srikanth-lingala** [comment]
> but is it possible to differentiate between a wrong CRC vs. wrong password?

It depends on the type of encryption used. For AES a wrong password can easily be deduced. But for Zip Standard encryption, this can be a bit tricky. But either way, you can get the exception type from `ZipException.getType()` and check if it is a `ZipException.Type.WRONG_PASSWORD` or `CHECKSUM_MISMATCH`.

**Comment by srikanth-lingala** [comment]
Yeah, like I wrote in my message above, according to specification there is no clear way to deduce for sure if the error is because of wrong password or wrong crc in case of Zip Standard encryption. AES on the other hand has a better approach. Unfortunately with Zip Standard, we can only take a guess, and zip4j returns a WRONG_PASSWORD error.

**Comment by RohdeSchwarz-SDC** [comment]
Thanks for clarification! Closing issue, as there is no bug ✅
