### ISSUE TITLE
Compression Method "deflate (enhanced)" (deflate64) Unsupported

### ISSUE THREAD

**Issue by bmlong137** [srikanth-lingala/zip4j#525]
Large ZIP files (2+ GB) created by the built-in Windows ZIP tool will use deflate64 when creating those ZIP files.  This is flat-out not supported by zip4j.  It errors with the expected:

```log
Caused by: net.lingala.zip4j.exception.ZipException: Unknown compression method
        at net.lingala.zip4j.model.enums.CompressionMethod.getCompressionMethodFromCode(CompressionMethod.java:52) ~[zip4j-2.10.0.jar:?]
        at net.lingala.zip4j.headers.HeaderReader.readLocalFileHeader(HeaderReader.java:539) ~[zip4j-2.10.0.jar:?]
```

This issue would only be resolved by adding support for that compression method.

**Comment by bmlong137** [comment]
I am going to look into adding this feature myself.

**Comment by bmlong137** [comment]
Here is a pull request with the feature added: https://github.com/srikanth-lingala/zip4j/pull/526
