### ISSUE TITLE
Issue find when we do gradlew.bat app:assembleRelease

### ISSUE THREAD

**Issue by lkhore** [srikanth-lingala/zip4j#533]
2024-01-16T06:28:27.8243241Z FAILURE: Build failed with an exception.
2024-01-16T06:28:27.8244317Z 
2024-01-16T06:28:27.8244896Z * What went wrong:
2024-01-16T06:28:27.8247004Z Could not determine the dependencies of task ':app:lintVitalReportRelease'.
2024-01-16T06:28:27.8250272Z > Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
2024-01-16T06:28:27.8251813Z    > Could not resolve net.lingala.zip4j:zip4j:2.+.
2024-01-16T06:28:27.8252370Z      Required by:
2024-01-16T06:28:27.8253033Z          project :app > project :react-native-zip-archive
2024-01-16T06:28:27.8253963Z       > Failed to list versions for net.lingala.zip4j:zip4j.
2024-01-16T06:28:27.8255718Z          > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml.
2024-01-16T06:28:27.8258068Z             > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
2024-01-16T06:28:27.8259016Z 
2024-01-16T06:28:27.8259164Z * Try:
2024-01-16T06:28:27.8259478Z > Run with --stacktrace option to get the stack trace.
2024-01-16T06:28:27.8260002Z > Run with --info or --debug option to get more log output.
2024-01-16T06:28:27.8260463Z > Run with --scan to get full insights.
2024-01-16T06:28:27.8260649Z 
2024-01-16T06:28:27.8260906Z * Get more help at https://help.gradle.org
2024-01-16T06:28:27.8261115Z 
2024-01-16T06:28:27.8261513Z Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
2024-01-16T06:28:27.8261963Z 
2024-01-16T06:28:27.8262743Z You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
2024-01-16T06:28:27.8263409Z 
2024-01-16T06:28:27.8263868Z See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
2024-01-16T06:28:27.8264363Z 
2024-01-16T06:28:27.8264598Z BUILD FAILED in 20s
2024-01-16T06:28:27.8264915Z 5 actionable tasks: 5 up-to-date
2024-01-16T06:28:28.4444101Z Error: The process 'C:\agents\_work\1\s\android\gradlew.bat' failed with exit code 1
2024-01-16T06:28:28.4446713Z     at ExecState._setResult (C:\agents\_work\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\3.231.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2024-01-16T06:28:28.4448076Z     at ExecState.CheckComplete (C:\agents\_work\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\3.231.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2024-01-16T06:28:28.4450336Z     at ChildProcess.<anonymous> (C:\agents\_work\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\3.231.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2024-01-16T06:28:28.4451474Z     at ChildProcess.emit (node:events:513:28)
2024-01-16T06:28:28.4451935Z     at maybeClose (node:internal/child_process:1100:16)
2024-01-16T06:28:28.4452803Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
2024-01-16T06:28:28.4482951Z ##[error]Code analysis failed. Gradle exit code: -1. Error: Error: The process 'C:\agents\_work\1\s\android\gradlew.bat' failed with exit code 1
2024-01-16T06:28:28.4532998Z ##[section]Finishing: gradlew app:assembleRelease

**Comment by lkhore** [comment]
Now it is working
