### ISSUE TITLE
unzip is failed - for getting inputStream for a file

### ISSUE THREAD

**Issue by amitkvmz** [srikanth-lingala/zip4j#66]
Caused by: java.lang.NoSuchMethodError: net.lingala.zip4j.model.ZipModel.setEndOfCentralDirectoryRecord(Lnet/lingala/zip4j/model/EndOfCentralDirectoryRecord;)V
	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:63)
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:831)
	at net.lingala.zip4j.ZipFile.getFileHeader(ZipFile.java:565)

**Comment by amitkvmz** [comment]
With java version 1.8.0_221

**Comment by amitkvmz** [comment]
I recompiled the project to get the updated artifact my current compiler. Now it's working.
