### ISSUE TITLE
Exception when copying zip archive to temp folder in junit test

### ISSUE THREAD

**Issue by WalterLeinert** [srikanth-lingala/zip4j#88]
zip4j version 2.2.2 from maven repo.

I'm trying to password protect an existing zip archive for download.
In my unit test I create the password protected zip archiv by name only which works.
When I try to specify an absolute temp folder (like C:\Users\e009602\AppData\Local\Temp\junit5212761713370497457) I'm getting the exception below.

I'm looping through the archive file headers to copy the archive. Is there a simpler way to create a password protected archive from an existinmg archive?

Regards,
Walter

Exception stack:
net.lingala.zip4j.exception.ZipException: net.lingala.zip4j.exception.ZipException: Zip headers not found. Probably not a zip file or a corrupted zip file
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:850)
	at net.lingala.zip4j.ZipFile.checkZipModel(ZipFile.java:861)
	at net.lingala.zip4j.ZipFile.addStream(ZipFile.java:392)
	at de.vkb.diagnostics.Zip4jTest.copyZipFile(Zip4jTest.java:106)
	at de.vkb.diagnostics.Zip4jTest.testCopyZip_Downloads(Zip4jTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: net.lingala.zip4j.exception.ZipException: Zip headers not found. Probably not a zip file or a corrupted zip file
	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:68)
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:847)
	... 29 more
Caused by: java.io.IOException: Negative seek offset
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:572)
	at net.lingala.zip4j.headers.HeaderReader.readEndOfCentralDirectoryRecord(HeaderReader.java:98)
	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:66)
	... 30 more

**Comment by srikanth-lingala** [comment]
> Is there a simpler way to create a password protected archive from an existing archive?

This will be a good candidate for a new feature in zip4j, but at the moment there is no direct/easy way to do it. You have to unpack the zip archive first and then add password to it again when you compress it. You can use streams to do it though. You don't necessarily have to unpack it to files.

You can do it with the code below:

```
public void applyPasswordToExistingZipFile() throws IOException {
  int readLen;
  byte[] b = new byte[4096];
  LocalFileHeader localFileHeader;

  try (ZipInputStream zipInputStream = new ZipInputStream(new FileInputStream(new File("sample.zip")));
       ZipOutputStream zipOutputStream = new ZipOutputStream(new FileOutputStream(new File("sample_password.zip")), "test".toCharArray());) {

    while ((localFileHeader = zipInputStream.getNextEntry()) != null) {
      ZipParameters zipParameters = buildZipParametersFromLocalFileHeader(localFileHeader);
      zipOutputStream.putNextEntry(zipParameters);

      while ((readLen = zipInputStream.read(b)) != -1) {
        zipOutputStream.write(b, 0, readLen);
      }

      zipOutputStream.closeEntry();
    }
  }
}

private ZipParameters buildZipParametersFromLocalFileHeader(LocalFileHeader localFileHeader) {
  ZipParameters zipParameters = new ZipParameters();
  zipParameters.setFileNameInZip(localFileHeader.getFileName());
  zipParameters.setCompressionMethod(localFileHeader.getCompressionMethod());
  zipParameters.setLastModifiedFileTime(localFileHeader.getLastModifiedTime());
  zipParameters.setEntryCRC(localFileHeader.getCrc());
  zipParameters.setEncryptFiles(true);
  zipParameters.setEncryptionMethod(EncryptionMethod.AES);
  return zipParameters;
}
```

Please note that some properties of the entries in zip might be lost in the process. For example, there is no way to keep the current file attributes when rewriting again. File attributes such as wether the file is hidden or the file permissions might be lost. If these values are critical to your application, then you should proceed with caution. As far as I can tell, the rest of the properties should be retained, although I would encourage you to test it yourself.

If you still have any issues, please post the code you use as well.

**Comment by WalterLeinert** [comment]
Hi Srikanth,

Thanks for your feedback and code sample. But due to certain reasons we decided not to use archive encryption but encryption of the contained pdf files 

Regards, Walter
